### ISSUE TITLE
Linux Browser Plugin

### ISSUE THREAD

**Issue by Diolinux** [flathub/com.obsproject.Studio#10]
Linux Browser plugin is a very useful tool for Linux Streamers, can you please add this functionality on this flatpak?

https://github.com/bazukas/obs-linuxbrowser

Regards

**Comment by TingPing** [comment]
No, that plugin looks massive since it bundles all of Chromium. I cannot support that. If somebody wants to package it in an optional extension let me know and I'll make an extension point for it.

**Comment by TingPing** [comment]
Other users have reported the binary they provide in their repo does work:

```
mkdir ~/.var/app/com.obsproject.Studio/config/obs-studio/plugins
tar -zxvf linuxbrowser0.6.0-obs22.0.2-64bit.tgz -C ~/.var/app/com.obsproject.Studio/config/obs-studio/plugins
```
