### ISSUE TITLE
wayland flatpak screencast capture freezes

### ISSUE THREAD

**Issue by ilippert** [flathub/com.obsproject.Studio#101]
Operating system and version: fedora 33

I use OBS flatpak commit
3f2cf2013982261626657eafd8b989a458d782f5a7a598040288bd6079a6f766

## Expected Behavior
If I use the Desktop Screencast Wayland/X11, select a display/window via the gnome screen share manager, the screencapture should work, i.e. capture should be updated.

## Current Behavior
the capture does not update

I checked older commits - in efbd5d2fc438ae7dd6602fca6beeba1e849cd920134d5c1339cbf040f48ab958 from flathub the behaviour is as expected.

sorry, this is the first time I report something here. Please let me know where to look precisely for more information that I should add here.

**Comment by sudopluto** [comment]
Having a similar issue.

Using Fedora 33, Gnome 3.38.4 on Wayland, and using pipewire enabled for audio. The video capture freezes when loading the preview, and stays frozen during recording of video. I am also using Intel Quicksync to encode on my integrated gpu, not sure if that makes a difference.

**Comment by ilippert** [comment]
Thanks, you put it into a more professional wording. That's what I experience.

**Comment by llndqvst** [comment]
Just want to add that I'm experiencing the exact same issue. Using Fedora 33 with the latest updates. Tried on both a laptop with intel iGPU and on a desktop computer using a Radeon 5600XT. Works fine using X.

**Comment by 0xf00f** [comment]
Silverblue F33 - Wayland Gnome
Same issue. 
I try the Desktop Screencast Wayland/X11 component, it captures the current screen and maybe few more frames, and then freezes. 
There is nothing in the log.

I suggest to rename the issue to: "... screencast freezes" instead of "... video freezes"

**Comment by jmou** [comment]
I had the same or similar issue. Using the beta fixed it for me. https://discourse.flathub.org/t/obs-studio-on-flathub-beta/690

**Comment by matheuscandido** [comment]
I have the same issue on Manjaro 21.

**Comment by sudopluto** [comment]
looks likes the diff is that the beta uses pipewire instead of xdg-portal
https://github.com/flathub/com.obsproject.Studio/commit/fed6478d4b7227f4a5f4979bc7471d678010887e

i guess we just wait for it to reach stable : )

**Comment by jmou** [comment]
For anyone curious there's a blog post with more details. Really impressive! https://feaneron.com/2021/03/30/obs-studio-on-wayland/

**Comment by sudopluto** [comment]
https://github.com/obsproject/obs-studio/releases/tag/27.0.0-rc1 its coming bois (and girls) : D

**Comment by vchernin** [comment]
This should be closed since OBS 27 was released for a while now

**Comment by GeorgesStavracas** [comment]
Indeed!
