### ISSUE TITLE
Wayland - Hotkeys are broken in multiple ways

### ISSUE THREAD

**Issue by Gambloide** [flathub/com.obsproject.Studio#102]
I wanted to set up some hotkeys to control some basic functions like muting/unmuting and switching scenes without the need for plugins, but stumbled across some severe limitations. I can also create separate tickets for these issues if preferred. But I assume the hotkey feature working as intended might ultimately be prevented by limitations of Wayland and underlying compositors anyway.

1. **Issue:** Configured hotkeys are not set in the input fields under Settings > Hotkeys. The input fields always stay empty: 
![image](https://user-images.githubusercontent.com/5939852/109429890-a31a5c80-79fe-11eb-9042-f58ca2500b18.png)
**Steps to reproduce:** Set a hotkey for a function.
**Expected behavior:** The set hotkey is shown in the input field next to the function to be called.
**Actual behavior:** The input field stays empty.
1. **Issue:** Only modifier keys and combinations of modifier keys can be set as hotkeys. Any other keys are ignored.
**Steps to reproduce:** Try to set a hotkey to any non modifier key
**Expected behavior:** A hotkey is set.
**Actual behavior:** No hotkey is set.
1. **Issue:** Hotkeys only work when OBS has focus.
**Steps to reproduce:** Set up a working hotkey and try to trigger it when OBS is not the focused application.
**Expected behavior:** The function bound to the hotkey is triggered.
**Actual behavior:**  The function bound to the hotkey is not triggered.

I am using the flathub beta branch on Fedora 33 with Gnome-shell/mutter.

``` bash
$ flatpak info com.obsproject.Studio

OBS Studio - Live streaming and video recording software

          ID: com.obsproject.Studio
         Ref: app/com.obsproject.Studio/x86_64/beta
        Arch: x86_64
      Branch: beta
     Version: 26.1.0
     License: GPL-2.0
      Origin: flathub-beta
  Collection: org.flathub.Beta
Installation: user
   Installed: 54,2 MB
     Runtime: org.kde.Platform/x86_64/5.15
         Sdk: org.kde.Sdk/x86_64/5.15

      Commit: 551fea42738de780b8d02d4a558a6509357976300adfcaccf908c9b9caca17aa
      Parent: f4562a2d441c2fe075cb874e56d89e8500e9c6a6013ede7c2e6e7340264c5b0b
     Subject: Add Wayland and X11 sockets (af9fda90)
        Date: 2020-12-28 19:30:59 +0000
```

**Comment by GeorgesStavracas** [comment]
There is no accepted protocol for global hotkeys yet, this is not an OBS Studio issue. And [old proposal](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/56) recently resurfaced, but it's still under discussion.

**Comment by Gambloide** [comment]
Thank you for the link to the proposal. 👍

Though the only the third of the three issues I wrote about are actually related to this as far as I understand.

Shouldn't we still be able to:
- set hotkeys with more than modifier keys and
- see which hotkeys are configured
  
regardless of their global applicability?

They could still be used inside OBS Studio when it has focus.
