### ISSUE TITLE
Browsersource not available in Flatpak

### ISSUE THREAD

**Issue by JJ4884** [flathub/com.obsproject.Studio#116]
I am currently using the Flatpak version of OBS due to Wayland support. As such, there is no option to add Browsersources for overlays and other items to OBS. Is there a way to fix this? Would I need to manually compile browsersource support? Also, obs-linuxbrowser is now defunct and directs people to OBS-Browser

**Comment by GeorgesStavracas** [comment]
The obs-browser plugin can't be enabled on Flatpak for now, both because the embedded Chromium conflicts with the Flatpak sandbox, and because CEF doesn't support Wayland yet.

**Comment by that1estonian** [comment]
> The obs-browser plugin can't be enabled on Flatpak for now, both because the embedded Chromium conflicts with the Flatpak sandbox, and because CEF doesn't support Wayland yet.

Hopefully gets fixed soon :crossed_fingers:

**Comment by GeorgesStavracas** [comment]
So, I managed to enable CEF on Flatpak with https://github.com/flathub/com.obsproject.Studio/commit/09cef8c5bed7388717ffa6141f54d3429e9cdbd9. It's available in the Flathub Beta branch.

However, please keep in mind that CEF + Wayland = 🔥️. On X11 it's probably fine, seems to work as expected. But on Wayland, it currently works out of sheer luck, and can break any time soon.

**Comment by that1estonian** [comment]
how does one switch to beta branch? :roll_eyes:

**Comment by that1estonian** [comment]
WebSocket Plugin does not work with the beta.

**Comment by HugLifeTiZ** [comment]
> WebSocket Plugin does not work with the beta.

Hey there, I'm the maintainer for the WebSocket flatpak, so if there's anything that needs to be changed, I can do it. Can you be more specific about in what way it doesn't work?

**Comment by that1estonian** [comment]
> > WebSocket Plugin does not work with the beta.
> 
> Hey there, I'm the maintainer for the WebSocket flatpak, so if there's anything that needs to be changed, I can do it. Can you be more specific about in what way it doesn't work? It may be more appropriate to open an issue on [the flatpak repo's issue tracker](https://github.com/flathub/com.obsproject.Studio.Plugin.WebSocket/issues).

Hey, I mean the plugin is installed, but not detected by OBS Studio beta. That's pretty much it :man_shrugging: I just wasn't sure if i should open a ticket against beta/test release.

**Comment by hfiguiere** [comment]
The plugin needs to be built on the beta branch to to work.

**Comment by HugLifeTiZ** [comment]
> The plugin needs to be built on the beta branch to to work.

I'm not sure I did it right, but I created a beta branch in my repo, changed the version and runtime version, then triggered a build and published it from the flathub build site. I don't know if it will actually show up in flathub-beta. Here's the flatpakref for the build: https://dl.flathub.org/build-repo/43328/com.obsproject.Studio.Plugin.WebSocket.flatpakref

**Comment by GeorgesStavracas** [comment]
The browser source has been enabled on the main Flathub branch, and will be available in a few hours from now. Thanks everyone.
