### ISSUE TITLE
[beta] libcef_dll_wrapper.a

### ISSUE THREAD

**Issue by hfiguiere** [flathub/com.obsproject.Studio#125]
Is there a reason to have libcef_dll_wrapper.a in the beta flatpak? This is a static library and it weigth 50MB (which is the size of the current stable flatpak)

**Comment by GeorgesStavracas** [comment]
I'll need to double check, but IIRC the browser plugin wouldn't work without it for some reason...

**Comment by hfiguiere** [comment]
That's would be very strange it is used past the build. A feel that it should be removed in the cleanup phase.

**Comment by hfiguiere** [comment]
I have tested removing it in the cleanup phase and the obs-browser plugin seems to work.

**Comment by GeorgesStavracas** [comment]
Done on the `beta` branch, will land on the `master` when OBS Studio officially releases.
