### ISSUE TITLE
ffmpeg ist not building with libvpx (vp9 encoder) 

### ISSUE THREAD

**Issue by arpu** [flathub/com.obsproject.Studio#13]
would it be possible to enable libvpx plz?

**Comment by TingPing** [comment]
So building ffmpeg with libvpx alone isn't enough, I also tested a host package (Arch) and it didn't have the option either.

So I'm unsure if its supported or what is needed for it.

**Comment by TingPing** [comment]
Oh, ffmpeg is hidden behind the advanced options!

`libvpx-vp9` is now there.

**Comment by arpu** [comment]
hmm will test this soon,  but it looks like the libs for libvpxare are not installed?

**Comment by TingPing** [comment]
```
>flatpak run --command=ls com.obsproject.Studio /usr/lib | grep vpx
libvpx.so.3
libvpx.so.3.0
libvpx.so.3.0.0
```

**Comment by arpu** [comment]
perfect thx a lot!
