### ISSUE TITLE
Virtual Camera Support

### ISSUE THREAD

**Issue by dada513** [flathub/com.obsproject.Studio#134]
I know there is #117 but OBS now provides this function natively without a plugin when the `v4l2loopback-dkms` package is installed on the host. Is that supported in this flatpak? I don't see a `Start Virtual Camera` button after installing that package (Tho normal obs from PPA works)

**Comment by GeorgesStavracas** [comment]
This is basically a duplicate of https://github.com/flathub/com.obsproject.Studio/issues/91

Flathub will support Virtual Camera starting from the 27 release, which is not out yet. Feel free to use the beta release meanwhile.
