### ISSUE TITLE
Flathub Plugins

### ISSUE THREAD

**Issue by GeorgesStavracas** [flathub/com.obsproject.Studio#135]
It is perfectly possible to add plugins to OBS Studio using Flatpak, and in fact there are a couple of plugins already available! However, there is currently no documentation; a custom patch on Flathub to manage these extensions; and overall a lack of visibility around it.

Publishing OBS Studio on Flathub has the potential to being the showcase of all these features, so it's a good idea to have a well-documented, simple process for plugin authors to publish their work here.

ACs:
 * [x] Discuss and formalize where the Flatpak extensions directory will be
 * [x] Upstream our only downstream patch after reaching agreement (https://github.com/obsproject/obs-studio/pull/4812)
 * [x] Create a plugin template for Flathub
 * [x] Document it all and make it accessible (README, official OBS Studio repository, etc)

**Comment by GeorgesStavracas** [comment]
After further inspection, I believe the current approach is good to be proposed upstream. It is currently composed of:

 1. Listing `/app/plugin` as one of the search paths in OBS Studio code (the downstream patch)
 2. An extension point that merges the `lib` and `share` directories at `/app/plugin`
 3. Plugins prefix their install paths to `/app/plugins/<plugin name>`

Flatpak then does the rest, and the .so files end up at `/app/plugin/lib/obs-plugins`, which is what's listed in OBS Studio source code.

**Comment by develroo** [comment]
Just out of curiosity, what is the manual way to add plugins to the OBS flatpak? It seems OBS usefulness is limited without a nice way to add useful functionality to it via plugins.

**Comment by GeorgesStavracas** [comment]
It's possible to manually add plugins by copying their shared libraries into `~/.var/app/com.obsproject.Studio/config/obs-studio/plugins`. This is now documented at https://github.com/flathub/com.obsproject.Studio/wiki/Plugins.
