### ISSUE TITLE
Unable to input Chinese/Japanese/Korean in OBS Studio

### ISSUE THREAD

**Issue by laichiaheng** [flathub/com.obsproject.Studio#14]
I have tried the snap version of OBS Studio, there is no input method problem with it, but I can't do that to the flatpak version of OBS Studio.
OS: Ubuntu 18.04

**Comment by TingPing** [comment]
I updated Qt to 5.11 in the upcoming update. Beyond that I don't think its anything to do with this package an dis probably something to discuss with the KDE/Qt folks.
