### ISSUE TITLE
It doesn't load the system fontcofig setting.

### ISSUE THREAD

**Issue by laichiaheng** [flathub/com.obsproject.Studio#15]
Here is the comparison of snap and flatpak, the flatpak one doesn't render the fonts like how the system does, the snap version which fonts is thinner is correct.
Why is it v0.0.1?
![2018-10-23 14-55-09](https://user-images.githubusercontent.com/9532105/47341696-4bec7a80-d6d4-11e8-8e8e-54c16d438f7c.png)

**Comment by TingPing** [comment]
Flatpak does pull in host fonts and to some degree configs. This is probably a discussion to have with https://github.com/flatpak/flatpak

**Comment by laichiaheng** [comment]
@TingPing The version of OBS Studio is wrong, why 0.0.1?

**Comment by TingPing** [comment]
I'd call that a bug with OBS' build system probably. It is the latest release.

**Comment by TingPing** [comment]
I just triggered a new build with the version fixed.
