### ISSUE TITLE
Package Droidcam plugin with adb

### ISSUE THREAD

**Issue by ravencodde** [flathub/com.obsproject.Studio#152]
I don´t know if that is a bug or I that don´t understand flatpaks works. I am trying install droidcam obs plugin, I put it on  my /home/user/.var/app/com.obsproject.Studio/config/obs-studio/plugins, Obs load it but droidcam cann´t found adb. I have adb installed on my system, I am using EndeavoarOS. 

I search on the Internet and I can´t resolve that, I so sorry if post that in wrong place. I need to know if are there some problems between extenal plugins OBS with OBS flatpak.

Thanks!

**Comment by TingPing** [comment]
OBS runs in a sandbox. Putting plugins in `~.var/app/com.obsproject.Studio/config/obs-studio/plugins` is more likely to fail than to work.

The best solution is somebody finding the time to package the plugin and ensure it works.

**Comment by ravencodde** [comment]
I will wait for that. I really would like to use this flatpak, but I removed it for now and install default package.  Thank you for replay @TingPing .

**Comment by hasrack** [comment]
You can use with wifi option with normal plugin. I am using it in flatpak version.

**Comment by hasrack** [comment]
> 
Normal plugin works with wifi option, just not with adb. I am using it with wifi option.

**Comment by ravencodde** [comment]
I had not problem use Wifi, it works very well. But I need to use adb. I don´t need to use adb anymore.  If some want close this issue, feel free. Thank for all of you that replay my post and try to help me!
