### ISSUE TITLE
No blackmagic support

### ISSUE THREAD

**Issue by sat3ll** [flathub/com.obsproject.Studio#16]
Using the non flatpak version of this software I am able to use my `Blackmagic Intensity Pro 4K` capture card.

With the flatpak version I get this in the log (absent in the non flatpak):
```
05:22:00.293: No blackmagic support
```

No overrides have been made to this flatpak.
Blackmagic drivers are installed and firmware up to date.

Relevant info:
```
$ flatpak --version 
Flatpak 1.0.6
$ screenfetch -n | grep OS
OS: Fedora 29 TwentyNine
```

**Comment by TingPing** [comment]
Looks like maybe just need to build the gstreamer plugin for it. I don't have this hardware of course so it will be impossible for me to test.

**Comment by sat3ll** [comment]
> > I think I already have it installed.
> 
> Libs on the host never matter.

It seems present in the runtime specified by the manifest.
```
$ find /var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.11/active/files/ | grep libgstdecklink.so
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.11/active/files/lib/gstreamer-1.0/libgstdecklink.so
```

**Comment by TingPing** [comment]
Well that eliminates the easy option =\

**Comment by sat3ll** [comment]
With `flatpak run --verbose com.obsproject.Studio` on the terminal I get this:
```
info: ---------------------------------
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
info: No blackmagic support
```
Any idea on how to get more info on this?

**Comment by TingPing** [comment]
What package provided `libDeckLinkAPI.so` on the host?

**Comment by sat3ll** [comment]
> What package provided `libDeckLinkAPI.so` on the host?


```
$ sudo dnf whatprovides '*libDeckLinkAPI.so'
desktopvideo-10.11.4-a9.x86_64 : Blackmagic Design Desktop Video 10.11.4 - Driver and Firmware Update Utility
```
This package is obtained from https://www.blackmagicdesign.com/support/family/capture-and-playback under the name **Desktop Video 10.11.4**.

I did some experimentation of my own (it works but I'm pretty sure it's not the right way):

1. I extracted the x86_64 .rpm package and did:
```
$ sudo cp -r /tmp/desktopvideo-10.11.4a9.x86_64/usr/lib64/blackmagic /tmp/desktopvideo-10.11.4a9.x86_64/usr/lib64/libDeckLinkAPI.so /var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.11/active/files/lib/
```
Essentially equivalent to copying `blackmagic/` and `libDeckLinkAPI.so` from host `/usr/lib64` to `/var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.11/active/files/lib/`.

**Comment by TingPing** [comment]
OK this is going to be tricky.

So it is of course proprietary so we cannot just put in this package. We can however add it to an extension that can be installed. The next problem is that it has no URL we can use, it generates a temporary download URL on the website that expires...

**Comment by sat3ll** [comment]
> The next problem is that it has no URL we can use, it generates a temporary download URL on the website that expires...

It can be done by scraping but I am not an expert at this. I tried using python with robobrowser and spynner to no avail, ended using selenium (working example: https://gist.github.com/sat3ll/aabd6abfb4e1618358165774ef8503f7). The only problem is that for selenium to work it requires Firefox or another browser (and naturally an X server + dependencies, maybe Xvfb can be used in the same manner as https://github.com/makinacorpus/spynner#running-spynner-without-x11.)

**Comment by TingPing** [comment]
It has to be a static url for `flatpak` to download it...

Honestly the most realistic solution is probably for somebody who doesn't care about violating their license to just rehost it..

**Comment by sat3ll** [comment]
>We can however add it to an extension that can be installed.

I'm thinking maybe a wiki page with instructions on how to build this "custom extension" could be a good workaround. Do you have any resources you can point to me on how to achieve this?

**Comment by TingPing** [comment]
I can make a page on it this weekend.

**Comment by TingPing** [comment]
Let me know how it works: https://github.com/flathub/com.obsproject.Studio/wiki/BlackMagic-Support

**Comment by sat3ll** [comment]
> Let me know how it works: https://github.com/flathub/com.obsproject.Studio/wiki/BlackMagic-Support

```
libc++.so.1: cannot open shared object file: No such file or directory
info: No blackmagic support
```
It can be found at `usr/lib64/blackmagic/DesktopVideo` from the .rpm. Maybe it's better including the *.so from this directory?

**Comment by TingPing** [comment]
Ouch, that is awful...

**Comment by TingPing** [comment]
Maybe one of the libs from the rpm or deb file links against the same abi we have. Could you maybe test that for me? I really don't want to start mixing multiple libc++'s in a process.

**Comment by sat3ll** [comment]
> Maybe one of the libs from the rpm or deb file links against the same abi we have. Could you maybe test that for me? I really don't want to start mixing multiple libc++'s in a process.

Pardon for asking but how do I do that?

**Comment by sat3ll** [comment]
> The hack you mentioned in your other comment is good enough to test: [#16 (comment)](https://github.com/flathub/com.obsproject.Studio/issues/16#issuecomment-441482611)

I can't seem to find `libc++(abi)` in org.kde.Platform. Should I attempt what discord flatpak is doing? (https://github.com/flathub/com.discordapp.Discord/blob/90d9f1a0c350b4d479738476e53fea4bba473a83/com.discordapp.Discord.json#L68)

The only lib that I could find in kde runtime was `libgcc_s.so.1`.

**Comment by TingPing** [comment]
Ah, I'll add it in a sec.

**Comment by TingPing** [comment]
Ok I pushed a change to just install the bundled libs. Building our own takes forever and I suspect users wouldn't appreciate it. Since you were right that libc++ isn't in the runtime its probably safe.

**Comment by sat3ll** [comment]
It works now, it even seems that copying `libgcc_s.so.1` isn't even required.

**Comment by TingPing** [comment]
Thanks for the help!
