### ISSUE TITLE
[BUG] OBS Studio 27.13 flatpak version doesn't open in Fedora workstation 34 after the update

### ISSUE THREAD

**Issue by hasrack** [flathub/com.obsproject.Studio#160]
I have updated obs studio few days ago through flatpak update. After the update it doesn't open at all. I have tested in X11 and wayland. It doesn't open anywhere. Other flatpak packages working just fine. 

Here is video demo 
https://youtu.be/IcIJrFx1FRs

OS: Fedora 34
Kernel version: 5.13.9
Flatpak version: 1.10.3

Thank you.

**Comment by FastOSlinux** [comment]
> 
still having a problem? here looks ok with GNOME/KDE
If no 
try to create a new user and test, to eliminate user configuration..

**Comment by hasrack** [comment]
It is working fine now.
