### ISSUE TITLE
[Fedora 35] Desktop Audio can not be recorded instead microphone is recorded independent of device setting

### ISSUE THREAD

**Issue by Mershl** [flathub/com.obsproject.Studio#167]
## Description
Indepedent of the device setting behind "desktop audio" the input will always source the physical microphone. Actual desktop audio can no longer be recorded.

No known workaround so far. Maybe a wireplumber (F35 specific) issue?

**Comment by FastOSlinux** [comment]
update to wireplumber-0.4.5-3.fc35, it's ok here

**Comment by Mershl** [comment]
Yep, can confirm. The update to wireplumber-0.4.5-3.fc35 fixed this issue.
