### ISSUE TITLE
[FR] git revert 6058b6a87f2e0a29e77ff42b7616690589a0ae9c

### ISSUE THREAD

**Issue by rayfoss** [flathub/com.obsproject.Studio#180]
Is there a way to add this line before the build process? Upstream is intentionally breaking the app when it detects the user has a folder named `/opt/google`, I'm not making this up.

https://github.com/obsproject/obs-studio/issues/5642

**Comment by GeorgesStavracas** [comment]
We avoid as much as possible modifying the original source, and very soon this repository will be archived since the Flathub releases will come from the OBS Studio community itself. If you think this commit is concerning, a revert should be coordinated upstream.
