### ISSUE TITLE
Can't Input Japanese from fcitx-mozc

### ISSUE THREAD

**Issue by nogajun** [flathub/com.obsproject.Studio#36]
Can't enter Japanese in Scene Name and Source Name from fcitx-mozc.

1. Add Scenes from add button.
2. It disappears input Japanese from fcitx-mozc.

![image](https://user-images.githubusercontent.com/15888/65690509-2a48ff80-e0aa-11e9-8757-5182ece1b068.png)

> Name                                                Application ID                                    Version                    Branch            Installation
> OBS Studio                                          com.obsproject.Studio                             24.0.1-modified            stable            system

- Operating System: Debian GNU/Linux 
- KDE Plasma Version: 5.14.5
- Qt Version: 5.11.3
- KDE Frameworks Version: 5.62.0
- Kernel Version: 5.2.0-2-amd64
- OS Type: 64-bit
- Processors: 8 × AMD Ryzen 5 2400G with Radeon Vega Graphics
- Memory: 13.7 GiB of RAM

**Comment by TingPing** [comment]
This is something to discuss at a lower level like the runtime or flatpak itself.
