### ISSUE TITLE
SSL/TLS support not included in OBS-Studio flatpak 24.0.3-modified

### ISSUE THREAD

**Issue by TheDavii** [flathub/com.obsproject.Studio#39]
I am unable to use the Flatpak to stream to Facebook Live, which requires rtmps as of 1 May 2019. Log shows:

```
[rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmps://rtmp-api.facebook.com:443/rtmp/...
10:21:28 AM.021: RTMP_Connect1, no SSL/TLS support
10:21:28 AM.021: [rtmp stream: 'adv_stream'] Connection to rtmps://rtmp-api.facebook.com:443/rtmp/ failed: -2
10:21:28 AM.021: ==== Streaming Stop ================================================
```
Host PC is Fedora 29, fully patched as of 2 November 2019.

**Comment by TheDavii** [comment]
These links to the OBS project [https://github.com/obsproject/obs-studio/wiki/Install-Instructions/0e9687d45f62fd26144cb6b6ff048d05cb641c9c#linux-build-directions](url) and Arch Linux bug report on the same issue [https://bugs.archlinux.org/task/62686](url) indicate that the issue is that the cmake build utility searches for mbedtls at compile time to resolve the SSL/TLS support issue.

**Comment by eszlari** [comment]
This should work now.
