### ISSUE TITLE
audio not working on linux mint

### ISSUE THREAD

**Issue by hlwsmith** [flathub/com.obsproject.Studio#47]
Audio not working on linux mint. No audio devices show up after installing version 24.0.5, was working with version 24.0.3. There's is not even an option to add an audio source to a scene.
I've built a regular .deb using tag 24.0.6 and this is also working well.

**Comment by TingPing** [comment]
CC @dgcampea

**Comment by dgcampea** [comment]
Can confirm.
Also noted on the OBS logs:
```
Source ID 'pulse_output_capture' not found
Failed to create source 'Desktop Audio'!
Source ID 'pulse_input_capture' not found
Failed to create source 'Mic/Aux'!
```
I doubt tag 24.0.6 fixes this since https://github.com/obsproject/obs-studio/compare/24.0.5...24.0.6 does not seem to mention anything related to audio. Could be a dependency update here causing issues, will need to investigate.

**Comment by dgcampea** [comment]
During OBS compilation:
```
CMake Warning at plugins/linux-pulseaudio/CMakeLists.txt:8 (find_package):
  By not providing "FindPulseAudio.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "PulseAudio", but CMake did not find one.

  Could not find a package configuration file provided by "PulseAudio" with
  any of the following names:

    PulseAudioConfig.cmake
    pulseaudio-config.cmake

  Add the installation prefix of "PulseAudio" to CMAKE_PREFIX_PATH or set
  "PulseAudio_DIR" to a directory containing one of the above files.  If
  "PulseAudio" provides a separate development package or SDK, be sure it has
  been installed.


-- PulseAudio not found, disabling PulseAudio plugin
```

**Comment by dgcampea** [comment]
It has nothing to do with https://github.com/flathub/com.obsproject.Studio/commit/6dff42602bcec421d15fceba1e92493b572d06eb (version 24.0.5, new deps, 5.14 runtime) since building the old commit https://github.com/flathub/com.obsproject.Studio/commit/aedb8149f6e1d8b9c6ae03417dae45954be621a0/version (version 24.0.3, 5.13 runtime) also results in the same log and no audio.
(using flatpak-builder 1.0.9)

@TingPing runtime bug?

**Comment by hlwsmith** [comment]
Should I report this bug elsewhere then, if it's a runtime issue?

**Comment by TingPing** [comment]
Probably a runtime regression, in the short term we can just use 5.13, and report it (probably against freedesktop-sdk).

**Comment by dgcampea** [comment]
> Probably a runtime regression, in the short term we can just use 5.13, and report it (probably against freedesktop-sdk).

Issue persists even with 5.13 runtime (both versions).

**Comment by FastOSlinux** [comment]
the same here, downgrade works for now

**Comment by TingPing** [comment]
Ok then it must be a regression in OBS' build system.

**Comment by eszlari** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/973

**Comment by FastOSlinux** [comment]
working now, tnks!

**Comment by hlwsmith** [comment]
It does seem to be the issue at https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/973 as it affects other projects using that SDK (Such as Kdenlive). I've solved the issue for me and my friend by building OBS old school style so I think this bug could be closed.

However a bug should be opened with whatever build set up/tool/code is being used to test this stuff before being released (and in the case of my friend automatically updated onto his compter breaking his setup and main use of that machine for a day). 

This is a major FAIL of flatpak.

**Comment by TingPing** [comment]
Its  closed because its fixed. No need to call the tool a failure because of a single bug...
