### ISSUE TITLE
ffmpeg is built with --enable-nonfree and as such can't be redistributed as a binary

### ISSUE THREAD

**Issue by ocrete** [flathub/com.obsproject.Studio#48]
The ffmpeg build distributed by Flathub is illegal. It included a copyright violation. You're not allowed to distribute binaries built with `--enable-nonfree`. In this case, it probably means removing fdk-aac and replacing it with another aac encoder (like the one built into ffmpeg itself).

**Comment by dgcampea** [comment]
ffmpeg aac encoder is decent (by: https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio).
I don't mind removing fdk-aac and defaulting to built-in.
@TingPing thoughts?

**Comment by ocrete** [comment]
Irrelevant of the FDK-AAC encoder freedomness, its license is not GPL compatible, so you can't distribute it with OBS .. or as a dependency of ffmpeg. The ffmpeg maintainers are quite clear of what they think of builds distributed with --enable-nonfree
