### ISSUE TITLE
libx264 codec not available in ffmpeg stream settings

### ISSUE THREAD

**Issue by jdloft** [flathub/com.obsproject.Studio#54]
In the drop down for video codec in the recording section for streaming a video via ffmpeg, the libx264 codec is missing. I have installed the ffmpeg, ffmpeg-full and openh264 runtimes.

The codec is present in the version distributed by RPM Fusion.

**Comment by TingPing** [comment]
I have `Encoder: x264`, is there somewhere else you refer to? The library is certainly there.

**Comment by jdloft** [comment]
This is when advanced is selected as the output mode. In simple I see "Software (x264)."

This is a screenshot of the version in RPM Fusion: 
![obs-rpmfusion](https://user-images.githubusercontent.com/8332322/77615253-76a7b780-6ef4-11ea-82ff-b98f2b67dc41.png)
and this is a screenshot of the same page with the version from the Flatpak:
![obs-flatpak](https://user-images.githubusercontent.com/8332322/77615271-81fae300-6ef4-11ea-8483-69a628ea4c0e.png)

**Comment by eszlari** [comment]
I guess obs has it's own x264 wrapper, but can also use ffmpeg.

Why do you want to encode x264 through ffmpeg?

**Comment by jdloft** [comment]
For streaming over an mpegts stream. I'm not familiar with the process these Flatpaks are built. Do we build a separate ffmpeg lib for this Flatpak separate from the ffmpeg runtime? If so it needs to be configured to have the x264 lib included at build time.

**Comment by jdloft** [comment]
Just got the update. Thanks for the help, much appreciated.
