### ISSUE TITLE
Instant crash on save settings

### ISSUE THREAD

**Issue by Pshemas** [flathub/com.obsproject.Studio#55]
While app works I'm getting repeatable crashes with Flathub's build of OBS. Each time I change a setting in the settings window and apply the app simply disappears. Crashes with no warning etc. The curious thing is that it stores the settings, even though it crashes.
Happens on my OpenSUSE Tumbleweed install, with Nvidia gpu.

**Comment by eszlari** [comment]
I cannot reproduce this (Kubuntu 19.10 + Nvidia GPU).

Maybe you could provide upstream with a stack trace:
https://www.figuiere.net/hub/blog/?2019/10/11/878-getting-a-stack-trace-out-of-a-flatpak

**Comment by Pshemas** [comment]
ok, weird - now when I installed it again (and after installing packages from regular OpenSUSE repos) the issue is gone (and yes, I'm sure I'm running a flatpak version - flatpak run com.obsproject.Studio :) ).
I'll look around for a clean system (fresh install) - if I find it and reproduce the crash I'll report back.

**Comment by TingPing** [comment]
I could reproduce it but it no longer happens (an update did happen between those).

**Comment by Pshemas** [comment]
I had another one of those (may be unrelated) while modifying filters on a source. But as with saving it seems to be now gone. Weird.

**Comment by TingPing** [comment]
I've not seen this problem since.
