### ISSUE TITLE
Unable to record screen

### ISSUE THREAD

**Issue by rombert** [flathub/com.obsproject.Studio#61]
I am trying out OBS and I tried adding a desktop source. All I got was a black rectangle with a red border. I tried capturing using the webcam and that worked.

I am running openSUSE Tumbleweed, Gnome 3.34.4/Xorg, NVidia proprietary driver 440.64 .

I've attached the terminal log, in case it provides some useful information: [obs.log](https://github.com/flathub/com.obsproject.Studio/files/4430422/obs.log).

**Comment by TingPing** [comment]
Which source type? Since you are on Xorg you can just use the XSHM one.

**Comment by rombert** [comment]
@TingPing - I was trying the _Desktop Screencast (Wayland / X11)_ source. That one is nicer for me since it allows me to capture specific windows. Not sure if there are any other differences I should consider, as I'm just starting to look into OBS.

**Comment by TingPing** [comment]
That is what Window Capture (XComposite) does.

Anyway your issue is likely that your `xdg-desktop-portal-gtk` is too old for Desktop Screencast, but since you are on X11 you can just use the other sources.

**Comment by rombert** [comment]
> your issue is likely that your xdg-desktop-portal-gtk is too old for Desktop Screencast,

1.6.0 FWIW

> since you are on X11 you can just use the other sources.

True, thank you for your help.

**Comment by TingPing** [comment]
> 1.6.0 FWIW

Hmm, well eitherway its an issue to report somewhere else.
