### ISSUE TITLE
"Hiccup" while screensharing

### ISSUE THREAD

**Issue by lionirdeadman** [flathub/com.obsproject.Studio#67]
Versions : F32 (Pipewire 0.3) with the OBS on Flathub-beta shipping 0.3

There is currently a hiccup where OBS doesn't receive frames for a certain amount of time. I think this might be due to a syncing issue. It seems that the preview is slowed down compared to what is on the screen and then it tries to resync with the current state of the screen which results in this hiccup effect.

This can be easily reproduced by looking at the preview while dragging the window in a circle, it will jump around in the preview.

**Comment by YaLTeR** [comment]
Yep, I've had the same issue for a while and I still have it on the latest flathub-beta OBS. Here's the issue I made originally: https://gitlab.gnome.org/feaneron/obs-xdg-portal/-/issues/5

Video demonstration from that issue: https://gitlab.gnome.org/feaneron/obs-xdg-portal/uploads/b87a0997bf31c5df720f88b5be39f901/out.mp4

**Comment by YaLTeR** [comment]
The issue seems solved on the new beta branch.

**Comment by lionirdeadman** [comment]
You're right, that feels so good. Closing then.
