### ISSUE TITLE
Issues w/ Nvidia 396.24 driver

### ISSUE THREAD

**Issue by ghost** [flathub/com.obsproject.Studio#7]
System Specifications:

OS: Ubunut 18.04
CPU: Intel i7-6700K
MEM: 32GiB DDR4
GPU: GTX 1080
MB: AsRock Pro MATX Z270

Terminal output:
```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /app/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /app/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /app/share/obs/obs-studio/themes/Dark.qss
Attempted path: share/obs/obs-studio/license/gplv2.txt
Attempted path: /app/share/obs/obs-studio/license/gplv2.txt
info: CPU Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
info: CPU Speed: 3999.565MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 32135MB Total, 26854MB Free
info: Kernel Version: Linux 4.15.0-23-generic
info: Distribution: Flatpak KDE Runtime 5.9
info: Portable mode: false
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 0.0.1 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
error: Failed to create OpenGL frame buffer config
error: Failed to create context!
error: device_create (GL) failed
error: Failed to initialize video.  Your GPU may not be supported, or your graphics drivers may need to be updated.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SwapBehavior(SingleBuffer), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))
Falling back to using screens root_visual.
info: Freeing OBS context data
info: == Profiler Results =============================
info: run_program_init: 10232 ms
info:  ┣OBSApp::AppInit: 0.789 ms
info:  ┃ ┗OBSApp::InitLocale: 0.638 ms
info:  ┗OBSApp::OBSInit: 109.031 ms
info:    ┣obs_startup: 19.357 ms
info:    ┗OBSBasic::OBSInit: 10.024 ms
info:      ┣OBSBasic::InitBasicConfig: 0.053 ms
info:      ┣OBSBasic::ResetAudio: 0.106 ms
info:      ┗OBSBasic::ResetVideo: 9.84 ms
info: obs_hotkey_thread(25 ms): min=0.057 ms, median=0.597 ms, max=2.138 ms, 99th percentile=0.839 ms, 100% below 25 ms
info: audio_thread(Audio): min=0.001 ms, median=0.03 ms, max=0.053 ms, 99th percentile=0.046 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25 ms): min=25.128 ms, median=25.713 ms, max=27.227 ms, 19.9488% within ±2% of 25 ms (0% lower, 80.0512% higher)
info: =================================================
info: Number of memory leaks: 172
```

**Comment by TingPing** [comment]
Is the driver installed? `flatpak update` would pull it in.

**Comment by Kroanvor** [comment]
I have tried that command with no luck. Same output as before.

**Comment by TingPing** [comment]
May be caused by this issue: https://github.com/flatpak/flatpak/issues/1786

**Comment by Kroanvor** [comment]
First off, excellent! However, I tried the workaround. 

Output:

Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /app/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /app/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /app/share/obs/obs-studio/themes/Dark.qss
Attempted path: share/obs/obs-studio/license/gplv2.txt
Attempted path: /app/share/obs/obs-studio/license/gplv2.txt
info: CPU Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
info: CPU Speed: 4062.781MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 32135MB Total, 29179MB Free
info: Kernel Version: Linux 4.15.0-23-generic
info: Distribution: Flatpak KDE Runtime 5.9
info: Portable mode: false
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 0.0.1 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
Gdk-Message: obs: Fatal IO error 11 (Resource temporarily unavailable) on X server :99.0.

**Comment by Shished** [comment]
I have tried the workaround and none opengl apps work with it. Shows the same X error.

**Comment by TingPing** [comment]
Well anyway this isn't an application problem so this discussion can continue on the linked issue.
