### ISSUE TITLE
Interesting behaviour with Gnome scaling enabled.

### ISSUE THREAD

**Issue by osirase** [flathub/com.obsproject.Studio#71]
Hi all,

First things first, thanks for this project. I really appreciate it.

I have a HTPC for my 4k TV, so I use gnome's experimental fractional integer scaling feature for nice clean scaling. OBS works, and pipewire does expose window and full screen sharing to OBS.

However, full screen rendering has what appears to be two 1920x1080 side by side, filling quarter of the 'red outline'. The red outline appears to be the actual res, 3840x2160.

I'll attach screenshots in the future, just making this issue now so I don't forget.

**Comment by osirase** [comment]
![image](https://user-images.githubusercontent.com/6511230/83958150-8b280900-a8c2-11ea-83f7-c4d4861bf3ca.png)

Example of the issue, but after scaling to window. Also notice how it's stretched horizontally.

![image](https://user-images.githubusercontent.com/6511230/83958120-3f755f80-a8c2-11ea-904f-82f9dca0d851.png)
Default settings was 'Preview Scaling' -> Canvas, and looks like above.

I don't know if this is technically possible, but it would be ideal if it was picked up as the resolution it's scaled it. In this case 1920x1080. I understand that this probably isn't possible as I'm using an experimental feature. My TV's scaling of 1920x1080 is awful, GNOME's factional scaling is perfect.

**Comment by osirase** [comment]
Some more information on my system.
OS: Fedora 32
Kernel: 5.6.15
CPU: Ryzen 3400g
Mesa: 20.0.0.7

**Comment by osirase** [comment]
So I've just attempted to do some screen sharing and connect via VNC, and this exact same behaviour is exhibited.

Is this a pipewire issue or a mutter issue? Happy to make the appropriate github issue but I'm not sure where to log it...

**Comment by osirase** [comment]
Opened a new issue here: https://gitlab.gnome.org/GNOME/mutter/-/issues/1131

**Comment by osirase** [comment]
Whoops, accidentally closed.

**Comment by vchernin** [comment]
I believe this should be fixed in Mutter (GNOME) since [this was merged](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1855).

@osirase assuming you’re on Fedora 34 now, does the issue occur on the latest GNOME 40.3? It seems that fix was in the GNOME 40 milestone so hopefully it’s fixed now, otherwise it will be in GNOME 41.

**Comment by GeorgesStavracas** [comment]
Regardless of whether this was backported or not, a Mutter fix landed. There's was nothing we could do on OBS side before, but now we at least know it should be fixed.
