### ISSUE TITLE
Package Advanced Screen Switcher plugin

### ISSUE THREAD

**Issue by RaneWallin** [flathub/com.obsproject.Studio#72]
I am trying to setup OBS on Clear Linux. I have found the flatpak installation runs well and in general has no issues, but I don't see a way to add a plugin. Based on my reading here it looks like this needs to be done when it is packaged? I would like to recommend including the Advanced Scene Switcher plugin. I included a link below. It's much better and more intuitive than the one that comes with OBS by default.

https://obsproject.com/forum/resources/advanced-scene-switcher.395/

**Comment by GeorgesStavracas** [comment]
Available as a Flatpak extension on Flathub now.
