### ISSUE TITLE
Add the input-overlay plugin

### ISSUE THREAD

**Issue by canalocaradoti** [flathub/com.obsproject.Studio#73]
Hi everyone, everything fine? I would like to suggest the addition of the input-overlay plugin, used in some Twitch lives and that could be a differentiator for the Flatpak version of OBS. The plugin works super well, I tested it on the Snap version and would think it would be great to have it on the Flapak version https://github.com/univrsal/input-overlay

**Comment by HugLifeTiZ** [comment]
I wanted to do that while adding the obs-websocket plugin, but it's kind of a pain to compile. Unlike obs-websocket, you can't tell it where the OBS sources are and you are expected to clone the repo as a subdirectory of OBS's source tree: https://github.com/univrsal/input-overlay/wiki/Compiling I'm not sure how to go about doing that just right now. But if I figure something out, I'll definitely get back. I'd rather use this plugin than a browser source + a gamepad viewer site.

**Comment by GeorgesStavracas** [comment]
This is provided as an extension now (see https://github.com/flathub/com.obsproject.Studio.Plugin.InputOverlay)

![Captura de tela de 2021-06-01 20-25-50](https://user-images.githubusercontent.com/3518204/120526122-3f158480-c3af-11eb-9ad8-86a688675988.png)

You can install it using GNOME Software, or any other app store that lists extensions, or even the command line program.
