### ISSUE TITLE
Add libsrt

### ISSUE THREAD

**Issue by VShell** [flathub/com.obsproject.Studio#77]
OBS can stream to SRT (https://obsproject.com/wiki/Streaming-With-SRT-Protocol) with a version of ffmpeg compiled `--with-libsrt`. [libsrt](https://github.com/Haivision/srt) has minimal dependencies (Tcl as a build dependency, and OpenSSL at runtime), so shouldn't be hard to add. I've attempted this but honestly can't wrap my head around flatpak's build system.

**Comment by dgcampea** [comment]
I've opened a PR to enable srt for ffmpeg but do note that you will need OBS at https://github.com/obsproject/obs-studio/commit/f1b97b78d66de6dd685808087f1b43fdbcb90037 to get it working.
