### ISSUE TITLE
Capture Hardware such as Blackmagic Intensity Pro is not detected by OBS Studio

### ISSUE THREAD

**Issue by Zachs-Kappler** [flathub/com.obsproject.Studio#93]
The current permission(s) for this Flatpak is blocking OBS Studio from seeing such hardware. I've tinkered around with things in flatseal and dug through the documentation to figure out how to just allow full access for video devices but haven't had any luck.

I'm using the latest x86-64 version of this flatpak as of writing, which has OBS 26.1.0.
I know this isn't a hardware or driver issue because OBS Studio can see and successfully access the capture card if I install it through apt from the PPA on the OBS website.

**Comment by TingPing** [comment]
I'm not very familiar with hardware like that but we already have the broadest permissions possible.

Have you followed this? https://github.com/flathub/com.obsproject.Studio/wiki/BlackMagic-Support

**Comment by sat3ll** [comment]
Support for BlackMagic devices in OBS is done via a proprietary library that gets installed with the drivers, you need to build the BlackMagic libs extension for flatpak OBS. You might need to tweak the archive filenames
https://github.com/flathub/com.obsproject.Studio/blob/18ecf5afcb8418d05ce07d3fb8a541a9c69357b9/com.obsproject.Studio.BlackMagicLibs.json#L15-L16
 since it hasn't been updated in a while.

**Comment by Zachs-Kappler** [comment]
I must have missed that bit. I've successfully modified the JSON to look for the files in the most recent stable release of the drivers, but currently all I see in OBS is lime green wherever I put the video from my Intensity Pro. I do however get audio through it just fine. Is there anything else I need to look at to get it working with the 11.7 drivers?

**Comment by sat3ll** [comment]
That's a non-flatpak bug, see https://github.com/obsproject/obs-studio/issues/3277

**Comment by Zachs-Kappler** [comment]
Ah, I see. I guess that means this can be marked as solved then since it isn't specific to this repo then.
