### ISSUE TITLE
I cant use obs

### ISSUE THREAD

**Issue by knightryry** [flathub/com.obsproject.Studio#99]
I cant use obs because im in chrome os. can you make it support Chrome os?
![Screenshot 2021-01-27 at 5 29 53 PM](https://user-images.githubusercontent.com/78123850/106076868-4d802680-60c5-11eb-8dc3-053dfe98a3c2.png)

**Comment by vchernin** [comment]
The [OBS Linux download website](https://obsproject.com/wiki/install-instructions#linux) says:
> Please note that OBS Studio is not fully working on Chrome OS and features like Screen and Window Capture do not work.   

I think it's unlikely there is anything we can do in the Flatpak to fix this issue. [That warning you see was added upstream](https://github.com/obsproject/obs-studio/pull/3239), and I'd suggest working with upstream if you want this fixed.

**Comment by GeorgesStavracas** [comment]
Agreed. Thanks @vchernin

**Comment by rayfoss** [comment]
the work around is to temporarily move /opt/google... then move it back after it starts. if you forget to do the latter, your container will be caput.
